---
  - name: Run script to get all aptitude installed 
    command: "sh {{ dps_home }}/get-apt-installed.sh {{ item }}"
    register: apt_out
    become: true
    when: current_library == "apt"

  - name: Run script to get all pip installed 
    command: "sh {{ dps_home }}/get-pip-installed.sh {{ item }}"
    register: pip_out
    become: true
    when: current_library == "pip"

  - name: Set apt comparsion variable
    set_fact: 
      searched_exists: "'{{ item }}': {{ apt_out.stdout_lines }}"
    when: current_library == "apt"

  - name: Set pip comparsion variable
    set_fact: 
      searched_exists: "'{{ item }}': {{ pip_out.stdout_lines }}"
    when: current_library == "pip"
  
  - name: Log the outputs of the script
    debug:
      msg: "{{ searched_exists }}"
  
  - name: Append to log file
    lineinfile:
      dest: "{{ dps_log_path }}"
      line: "{{ searched_exists }}"
      insertafter: EOF

  # - name: Run script to get all pip installed 
  #   script: "/{{ dps_home }}/get-pip-installed.sh"
  #   register: out
  #   set_fact:
  #     exists: "{{ out.stdout_lines }}"